[project]
name = "model-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.14.0",
    "autopep8>=2.3.2",
    "jupyter>=1.1.1",
    "llama-cpp-python>=0.3.33",
    "notebook>=7.6.0",
    "numpy>=2.5.1",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "torch>=2.13.0",
    "transformers>=5.13.1",
]
