steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'Dockerfile.runtime', '--build-arg', 'BASE_IMAGE=${_BASE_IMAGE}', '-t', '${_IMAGE}', '.']
images: ['${_IMAGE}']
options:
  machineType: E2_HIGHCPU_8
timeout: 1200s
