"""
Tier 2 Tools Node — executes tool calls in the LangGraph ReAct agent loop.
"""

from __future__ import annotations

import logging
from typing import Any
from langchain_core.messages import ToolMessage

from ...services.database import DatabaseService
from ...cloud.tier2_agent_tools import build_tier2_tools
from ...backend.audit_log import audit_from_state
from ..state import JarvisState

logger = logging.getLogger(__name__)


class Tier2ToolsNode:
    """Executes tool calls generated by Tier2AgentNode and appends ToolMessages."""

    def __init__(self, db: DatabaseService | None = None) -> None:
        self.db = db or DatabaseService()

    def __call__(self, state: JarvisState) -> dict[str, Any]:
        uid = state.get("uid", "")
        agent_messages = list(state.get("agent_messages", []))
        audit = audit_from_state(state, self.db)
        event_id = state.get("event_id", "")

        if not agent_messages:
            return {}

        last_msg = agent_messages[-1]
        tool_calls = getattr(last_msg, "tool_calls", [])
        if not tool_calls:
            return {}

        tools = build_tier2_tools(self.db, uid)
        tool_map = {t.name: t for t in tools}

        tool_messages: list[ToolMessage] = []
        changed_records = list(state.get("changed_records", []))

        for call in tool_calls:
            tool_name = call.get("name", "")
            tool_args = call.get("args", {})
            call_id = call.get("id", tool_name)

            t = tool_map.get(tool_name)
            if not t:
                res_content = f"Error: Tool '{tool_name}' is not an allow-listed tool."
            else:
                try:
                    res_content = str(t.invoke(tool_args))
                    # Check if an ID was created/modified
                    if "ID:" in res_content:
                        import re
                        m = re.search(r"ID:\s*([a-zA-Z0-9_-]+)", res_content)
                        if m:
                            changed_records.append(m.group(1))
                except Exception as e:
                    logger.error("Tool execution failed: %s with args %s: %s", tool_name, tool_args, e)
                    res_content = f"Error executing {tool_name}: {e}"

            audit.log(
                node_name="tier2_tools",
                action=f"tool_executed:{tool_name}",
                category="CRUD",
                event_id=event_id,
                input_summary={"args": tool_args},
                output_summary={"result": res_content[:200]},
            )

            tool_messages.append(
                ToolMessage(content=res_content, tool_call_id=call_id, name=tool_name)
            )

        updated_messages = agent_messages + tool_messages

        return {
            "agent_messages": updated_messages,
            "changed_records": changed_records,
        }
