"""
Tier 1 Tools Node — executes physical context tools in the LangGraph Tier 1 agent loop.
"""

from __future__ import annotations

import logging
from typing import Any
from langchain_core.messages import ToolMessage

from ...services.database import DatabaseService
from ...cloud.tier1_agent_tools import build_tier1_tools
from ...backend.audit_log import audit_from_state
from ..state import JarvisState

logger = logging.getLogger(__name__)


class Tier1ToolsNode:
    """Executes context tools generated by Tier1AgentNode and appends ToolMessages."""

    def __init__(self, db: DatabaseService | None = None) -> None:
        self.db = db or DatabaseService()

    def __call__(self, state: JarvisState) -> dict[str, Any]:
        uid = state.get("uid", "")
        agent_messages = list(state.get("tier1_messages", []))
        audit = audit_from_state(state, self.db)
        event_id = state.get("event_id", "")

        if not agent_messages:
            return {}

        last_msg = agent_messages[-1]
        tool_calls = getattr(last_msg, "tool_calls", [])
        if not tool_calls:
            return {}

        tools = build_tier1_tools(self.db, uid)
        tool_map = {t.name: t for t in tools}

        tool_messages: list[ToolMessage] = []

        for call in tool_calls:
            tool_name = call.get("name", "")
            tool_args = call.get("args", {})
            call_id = call.get("id", tool_name)

            t = tool_map.get(tool_name)
            if not t:
                res_content = f"Error: Tool '{tool_name}' not recognized."
            else:
                try:
                    res_content = str(t.invoke(tool_args))
                except Exception as e:
                    logger.error("Tier 1 tool execution failed: %s: %s", tool_name, e)
                    res_content = f"Error: {e}"

            audit.log(
                node_name="tier1_tools",
                action=f"tool_executed:{tool_name}",
                category="CONTEXT",
                event_id=event_id,
                input_summary={"args": tool_args},
                output_summary={"result": res_content[:200]},
            )

            tool_messages.append(
                ToolMessage(content=res_content, tool_call_id=call_id, name=tool_name)
            )

        return {
            "tier1_messages": agent_messages + tool_messages,
        }
