// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web; // Windows uses web config
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLataEz-wpVABwr3xlabUnUA4VYfJ1Zg0',
    appId: '1:738377286533:web:782d680520a255674f3aec',
    messagingSenderId: '738377286533',
    projectId: 'gen-lang-client-0513238373',
    authDomain: 'gen-lang-client-0513238373.firebaseapp.com',
    storageBucket: 'gen-lang-client-0513238373.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY0Gv-tmWwid-PpLZK9OpBfcURWMukgF8',
    appId: '1:738377286533:android:1897a2728fb8399d4f3aec',
    messagingSenderId: '738377286533',
    projectId: 'gen-lang-client-0513238373',
    storageBucket: 'gen-lang-client-0513238373.firebasestorage.app',
  );
}